/*
 * Copyright (C) 2022 The LineageOS Project
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#pragma once

/*CUR,DEFAULT,MIN,MAX*/
#define VALUE_TYPE_SIZE 6
#define VALUE_GRIP_SIZE 9
#define MAX_BUF_SIZE 256
#define BTN_INFO 0x152
#define MAX_TOUCH_ID 10
#define RAW_BUF_NUM 4
#define THP_CMD_BASE 1000

enum MODE_CMD {
    SET_CUR_VALUE = 0,
    GET_CUR_VALUE,
    GET_DEF_VALUE,
    GET_MIN_VALUE,
    GET_MAX_VALUE,
    GET_MODE_VALUE,
    RESET_MODE,
    SET_LONG_VALUE,
};

enum MODE_TYPE {
    TOUCH_GAME_MODE = 0,
    TOUCH_ACTIVE_MODE = 1,
    TOUCH_UP_THRESHOLD = 2,
    TOUCH_TOLERANCE = 3,
    TOUCH_AIM_SENSITIVITY = 4,
    TOUCH_TAP_STABILITY = 5,
    TOUCH_EXPERT_MODE = 6,
    TOUCH_EDGE_FILTER = 7,
    TOUCH_PANEL_ORIENTATION = 8,
    TOUCH_REPORT_RATE = 9,
    TOUCH_FOD_ENABLE = 10,
    TOUCH_AOD_ENABLE = 11,
    TOUCH_RESIST_RF = 12,
    TOUCH_IDLE_TIME = 13,
    TOUCH_DOUBLETAP_MODE = 14,
    TOUCH_GRIP_MODE = 15,
    TOUCH_FODICON_ENABLE = 16,
    TOUCH_NONUI_MODE = 17,
    TOUCH_DEBUG_LEVEL = 18,
    TOUCH_POWER_STATUS = 19,
    TOUCH_MODE_NUM = 20,
    THP_LOCK_SCAN_MODE = THP_CMD_BASE + 0,
    THP_FOD_DOWNUP_CTL = THP_CMD_BASE + 1,
    THP_SELF_CAP_SCAN = THP_CMD_BASE + 2,
    THP_REPORT_POINT_SWITCH = THP_CMD_BASE + 3,
    THP_HAL_INIT_READY = THP_CMD_BASE + 4,
};
